name: Streamlit App Workflow

on:
  push:
    branches: [main]  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Run the workflow on Ubuntu machines
    steps:
    - uses: actions/checkout@v3  # Checkout the code from the repository
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify your desired Python version
    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install required packages from requirements.txt
    - name: Build Streamlit app
      run: streamlit run app.py  # Build the Streamlit app (optional, might not be necessary)
    - name: Deploy to Streamlit Cloud
      uses: streamlit/deploy@main
      with:
        # Replace with your repository URL (if not already fetched)
        repo_url: https://github.com/omartarek000/-Named-Entity-Recognition-NER-and-Sentence-Completion
        # Optional: Specify access token if private repository (see Streamlit Cloud documentation)
        # token: ${{ secrets.STREAMLIT_CLOUD_TOKEN }}
