name: Streamlit App Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Streamlit app
        run: |
          nohup streamlit run main.py --server.port 8501 --server.headless True &
          sleep 10  # Wait for a few seconds to allow the app to start

      - name: Check if Streamlit app is running
        run: |
          if curl -s --head  --request GET http://localhost:8501 | grep "200 OK" > /dev/null; then 
            echo "Streamlit app is running."
          else
            echo "Streamlit app is not running."
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()  # Only run deploy if the build was successful
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Streamlit Cloud 
        uses: streamlit/deploy@main
        with:
          env_name: -Named-Entity-Recognition-NER-and-Sentence-Completion
